In [49]:
import psycopg2
import pandas as pd

In [50]:
DBNAME = "test"
HOST = "35.202.86.236"
USER = "alex"
PASSWORD = "alex"
PORT = "5432"

conn = psycopg2.connect(dbname=DBNAME, user=USER, password=PASSWORD, host=HOST, port=PORT)

In [51]:
cursor = conn.cursor()

In [52]:
cursor.execute("""
    SELECT 
        log_id,
        protein,
        carbohydrates,
        fats,
        user_uuid,
        calories,
        servings,
        log_date,
        food_name,
        image_path,
        serving_size,
        group_id
    FROM food_log
    ORDER BY user_uuid DESC
""")

records = cursor.fetchall()

# Create a DataFrame from the fetched records
df = pd.DataFrame(records, columns=[
    'log_id',
    'protein',
    'carbohydrates',
    'fats',
    'user_uuid',
    'calories',
    'servings',
    'log_date',
    'food_name',
    'image_path',
    'serving_size',
    'group_id'
])

print(df)

      log_id  protein  carbohydrates  fats  \
0       1189        2             16     1
1       1199        5             25     4
2       1198        0             35     0
3       1188       12              1    10
4       1197        2             18     6
...      ...      ...            ...   ...
1972    1724        2             22     0
1973    1725       12              2     6
1974    1726        5             25     5
1975    1727       52             52    10
1976    1719        7             54    18

                                 user_uuid  calories  servings  \
0     ffdbad8d-b84c-4837-b216-b78780cb5765        70         1
1     ffdbad8d-b84c-4837-b216-b78780cb5765       150         1
2     ffdbad8d-b84c-4837-b216-b78780cb5765       130         1
3     ffdbad8d-b84c-4837-b216-b78780cb5765       140         1
4     ffdbad8d-b84c-4837-b216-b78780cb5765       130         1
...                                    ...       ...       ...
1972  02e0403e-617d-4cdd-969e-a6c1cb7c7b1b       102         1
1973  02e0403e-617d-4cdd-969e-a6c1cb7c7b1b       106         1
1974  02e0403e-617d-4cdd-969e-a6c1cb7c7b1b       150         1
1975  02e0403e-617d-4cdd-969e-a6c1cb7c7b1b       520         2
1976  02e0403e-617d-4cdd-969e-a6c1cb7c7b1b       395         1

                log_date              food_name image_path serving_size  \
0    2024-02-05 02:04:26                  Salsa       None        1 cup
1    2024-02-05 02:08:32         Overnight Oats       None      1/2 cup
2    2024-02-05 02:07:58    Strawberry Lemonade       None      8 fl oz
3    2024-02-05 02:04:26               Two Eggs       None       2 eggs
4    2024-02-05 02:07:38       chocolate cookie       None     1 cookie
...                  ...                    ...        ...          ...
1972 2024-03-04 12:59:52                   Rice       None      1/2 cup
1973 2024-03-04 13:02:10       Chicken Shawarma       None          2oz
1974 2024-03-04 13:02:29  Mediterranean veggies       None        1 cup
1975 2024-03-04 13:04:22             Core Power       None     1 bottle
1976 2024-03-04 12:58:46         In N Out fries       None      1 order

                                               group_id
0     20240205020426ffdbad8d-b84c-4837-b216-b78780cb...
1     20240205020832ffdbad8d-b84c-4837-b216-b78780cb...
2     20240205020758ffdbad8d-b84c-4837-b216-b78780cb...
3     20240205020426ffdbad8d-b84c-4837-b216-b78780cb...
4     20240205020738ffdbad8d-b84c-4837-b216-b78780cb...
...                                                 ...
1972  2024030412595202e0403e-617d-4cdd-969e-a6c1cb7c...
1973  2024030413021002e0403e-617d-4cdd-969e-a6c1cb7c...
1974  2024030413022902e0403e-617d-4cdd-969e-a6c1cb7c...
1975  2024030413042202e0403e-617d-4cdd-969e-a6c1cb7c...
1976  2024030412584602e0403e-617d-4cdd-969e-a6c1cb7c...

[1977 rows x 12 columns]

In [53]:
cursor.execute("""
SELECT
    food_log.user_uuid,
    COUNT(food_log.user_uuid) AS count,
    users.email
FROM
    food_log
JOIN
    users ON food_log.user_uuid = users.user_uuid
GROUP BY
    food_log.user_uuid,
    users.email
ORDER BY
    count DESC
LIMIT 10
""")

records = cursor.fetchall()

# Create a DataFrame from the fetched records
df = pd.DataFrame(records, columns=[
    'user_uuid',
    'count',
    'email'
])

df

,user_uuid,count,email
0,9b8e372a-b5d4-4771-8741-511bae5d9193,350,landonpattison@gmail.com
1,4811183b-9d95-4351-b1ab-d6d63634b43f,245,jwjordan92@gmail.com
2,d01e0692-9b8e-4261-a3ab-70b0e9bf3dd3,201,jp4mmxxyj8@privaterelay.appleid.com
3,578ef529-0a26-410c-8741-d2f8fc34e914,186,willpollick@comcast.net
4,41377c23-b3e6-4c1b-9a2d-3e379c9435ac,173,srilokh.karuturi@gmail.com
5,42e3ccb2-4a04-486c-a37e-872eda985838,73,jeffpattison8@gmail.com
6,560c2ba7-adec-498e-b0de-e308ad7f183f,55,pattisonjayd7@gmail.com
7,d12e850f-7683-44be-a11e-573ec7ceb1e8,49,jtxvgb6hbp@privaterelay.appleid.com
8,b88afd62-6c34-4dd9-bb59-7af505cc0e20,37,hnfcr2grb8@privaterelay.appleid.com
9,c332c59c-36f1-4245-a9d4-2c14cdcc0023,33,shanaya.vakil@gmail.com

,user_uuid,last_eaten,first_eaten,days_between
0,9b8e372a-b5d4-4771-8741-511bae5d9193,2024-04-29 16:52:43,2023-06-28 01:23:43,306